Repository jadudm/cms-htmd, pull requests merged in 2020-10, with the labels that each got.

#1 Create Lessons “visibility-medium-1-test-lesson”
  _lessons/visibility-medium-1-test-lesson.md
Labels: netlify-cms/pending_publish

#3 Create Lessons “outcomes-low-1-all-about-modules-2”
  _lessons/outcomes-low-1-all-about-modules-2.md
Labels: netlify-cms/draft

#2 Create Lessons “development-medium-1-all-the-excitement-1”
  _lessons/development-medium-1-all-the-excitement-1.md
Labels: netlify-cms/pending_review

#6 Create Lessons “2/test-lesson”
  collections/_courses/2/test-lesson.md
Labels: netlify-cms/pending_publish

#8 Update Lesson “1/kickoff”
  collections/_courses/1/kickoff.md
Labels: netlify-cms/pending_publish

#11 Update Course One “overview”
  collections/_one/overview.md
Labels: netlify-cms/pending_publish

#17 Update Course One “outcomes”
  collections/_one/outcomes.md
Labels: netlify-cms/pending_publish

#18 Update Course One “outcomes”
  collections/_one/outcomes.md
Labels: netlify-cms/pending_publish

#12 Update Course One “capacity”
  collections/_one/capacity.md
Labels: netlify-cms/pending_publish
